# Generated by the Live Palette addon from res://live_palette/*.tres.
# Do not edit — it is rewritten whenever a palette changes.
class_name LivePalette

## The constants are the "Default" variant; switching variants at runtime goes
## through the LivePaletteRuntime autoload, which re-applies bound properties.
const INTERACTIONS := Color(0.8352941, 0.8039216, 0.007843138, 0.41960785)
const INTERACTORS := Color(0.8901961, 0.5647059, 0.007843138, 0.41960785)
const SPAWN := Color(0.9529412, 0.26666668, 0, 0.41960785)

## Palette name -> color, for lookups by a name held in a variable.
## Prefer the constants above: they are checked at compile time.
const BY_NAME := {
	"Interactions": INTERACTIONS,
	"Interactors": INTERACTORS,
	"Spawn": SPAWN,
}

## Variant name -> {name -> color}, for reading a variant you are not on.
const VARIANTS := {
	"Default": {
		"Interactions": Color(0.8352941, 0.8039216, 0.007843138, 0.41960785),
		"Interactors": Color(0.8901961, 0.5647059, 0.007843138, 0.41960785),
		"Spawn": Color(0.9529412, 0.26666668, 0, 0.41960785),
	},
}


static func color(p_name: StringName) -> Color:
	var key := str(p_name)
	if BY_NAME.has(key):
		return BY_NAME[key]
	push_warning("LivePalette: no color named '%s'" % p_name)
	return Color.WHITE


static func has_color(p_name: StringName) -> bool:
	return BY_NAME.has(str(p_name))


## A color from a specific variant, falling back to the base variant.
static func color_in(p_variant: StringName, p_name: StringName) -> Color:
	var table: Dictionary = VARIANTS.get(str(p_variant), {})
	if table.has(str(p_name)):
		return table[str(p_name)]
	return color(p_name)


static func variant_names() -> PackedStringArray:
	return PackedStringArray(VARIANTS.keys())
